msrv = "1.89"
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 7
type-complexity-threshold = 300
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
